language:
- python
python:
- '3.6'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: lnqRwBG055CRkhdLSCypuHPOZaN9SC3Oq2f7mSvpI1EqoGsim8LypbDe2LBxhgM0VPCAHmD8iLVBPBVg/QCo3AtUHmLzWEQELyzlIP6O+x2ilJ/0vHPCQB5A9i6pDUEWFe0zNg2XZ1fVRStCiQL9dNVjKwwyiXMlTqJRBfAWSzIHWcvo8kQcwrZ1wJaIWe0Gp6cuUXd0HZ41EwpJ+MI8zNg0hm9RMlvbia+uzouw4O0yvUVKWsdaj5+Yj4SRhKrbfqM5sEGXWhnGYv7LAc7Pk3sW17P2A0V87dup0KRRHuLU3DPwHVP/7wYYLX4enOXezVP4V6wL//ocM3dEkV4ufM18x2zQs//0wXU+iA3w3s3HvF/v5ENJdFT0Z5BSuuOYWXKIV595npzlrHg1kqcUDDB1y/e83LRVvpdN1exhaYPOznywcuSzCX7nl4JXNhA9fSS28TPp9Tph3MDgbj7/Z779O20pg3MNVKReUDrw6evw3j9kaQw33ldQJNp247T/fc19a5jSMqrKgMiynkIdtZuHFEHbxu9wbMm5E4H2s5LfNmIaP9Q6c0cCydp04oQWC/eSmqiy1jYmUMsknzHcIz7BGcvVLIxYAHfQWpfhiHnOpukX57BImCA4TYgidqT8k7fd79o68CfnWw/HVQCG3jQlFI5UmuDizL4H/OTDLRI=
  app: arcane-wave-80329
  on:
    branch: master
    python: '3.6'
    repo: LordNouda/FlaskTaskr
